# Generated by Django 5.1.2 on 2024-10-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_team_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_team",
                    models.IntegerField(blank=True, null=True, verbose_name="自チームのスコア"),
                ),
                (
                    "score_opponent",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="相手チームのスコア"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("win", "勝ち"), ("lose", "負け"), ("draw", "引き分け")],
                        max_length=20,
                        verbose_name="試合結果",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="内容"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="events.event",
                        verbose_name="イベント",
                    ),
                ),
            ],
            options={"db_table": "matches", "ordering": ["-event__date"],},
        ),
    ]
