# Generated by Django 5.1.2 on 2024-10-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_team_id"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="event",
            field=models.OneToOneField(
                db_column="event_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match",
                to="events.event",
                verbose_name="イベント",
            ),
        ),
    ]
