# Generated by Django 5.1.2 on 2024-10-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_alter_match_event"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team",
            field=models.ForeignKey(
                db_column="team_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="teams.team",
                verbose_name="チーム",
            ),
        ),
    ]
