# Generated by Django 5.1.2 on 2024-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="name",),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="メールアドレス"
            ),
        ),
    ]
