# Generated by Django 5.1.2 on 2024-10-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("practice", "練習"), ("game", "試合")],
                        max_length=50,
                        verbose_name="イベントタイプ",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("date", models.DateField(verbose_name="日付")),
                ("time", models.TimeField(verbose_name="時間")),
                ("location", models.CharField(max_length=100, verbose_name="場所")),
                ("detail", models.TextField(blank=True, verbose_name="詳細")),
            ],
            options={"db_table": "events",},
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "出席"),
                            ("absent", "欠席"),
                            ("undecided", "未定"),
                        ],
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="events.event",
                        verbose_name="イベント",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "unique_together": {("user_id", "event_id")},
            },
        ),
    ]
