# Generated by Django 5.1.2 on 2024-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="first_name",),
        migrations.RemoveField(model_name="customuser", name="is_staff",),
        migrations.RemoveField(model_name="customuser", name="last_name",),
        migrations.AddField(
            model_name="customuser",
            name="bat_throw",
            field=models.CharField(
                choices=[
                    ("RR", "右投げ右打ち"),
                    ("RL", "右投げ左打ち"),
                    ("LR", "左投げ右打ち"),
                    ("LL", "左投げ左打ち"),
                ],
                default="RR",
                max_length=2,
                verbose_name="投打",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="jersey_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="背番号"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="名前"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[("P", "ピッチャー"), ("C", "キャッチャー"), ("IF", "内野手"), ("OF", "外野手")],
                default="Unknown",
                max_length=50,
                verbose_name="ポジション",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="役割"
            ),
        ),
    ]
