# Generated by Django 5.1.2 on 2024-10-30 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0003_match_team"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HitterStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50, verbose_name="ポジション")),
                ("order", models.IntegerField(verbose_name="打順")),
                ("plate_appearances", models.IntegerField(verbose_name="打席数")),
                ("at_bats", models.IntegerField(verbose_name="打数")),
                ("hits", models.IntegerField(verbose_name="ヒット")),
                ("doubles", models.IntegerField(verbose_name="二塁打")),
                ("triples", models.IntegerField(verbose_name="三塁打")),
                ("home_runs", models.IntegerField(verbose_name="本塁打")),
                ("rbi", models.IntegerField(verbose_name="打点")),
                ("runs", models.IntegerField(verbose_name="得点")),
                ("strikeouts", models.IntegerField(verbose_name="三振")),
                ("walks", models.IntegerField(verbose_name="四球")),
                ("hbp", models.IntegerField(verbose_name="死球")),
                ("sac_bunt", models.IntegerField(verbose_name="犠打")),
                ("sac_fly", models.IntegerField(verbose_name="犠飛")),
                ("steals", models.IntegerField(verbose_name="盗塁")),
                ("caught_stealing", models.IntegerField(verbose_name="盗塁死")),
                ("gdp", models.IntegerField(verbose_name="併殺打")),
                ("errors", models.IntegerField(verbose_name="失策")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matches.match",
                        verbose_name="試合",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="選手",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="チーム",
                    ),
                ),
            ],
            options={"db_table": "hitter_stats",},
        ),
        migrations.CreateModel(
            name="PitcherStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("innings_pitched", models.FloatField(verbose_name="投球回")),
                ("plate_appearances", models.IntegerField(verbose_name="打席数")),
                ("at_bats", models.IntegerField(verbose_name="打数")),
                ("hits_allowed", models.IntegerField(verbose_name="被安打")),
                ("doubles_allowed", models.IntegerField(verbose_name="被二塁打")),
                ("triples_allowed", models.IntegerField(verbose_name="被三塁打")),
                ("home_runs_allowed", models.IntegerField(verbose_name="被本塁打")),
                ("strikeouts", models.IntegerField(verbose_name="三振")),
                ("walks", models.IntegerField(verbose_name="四球")),
                ("hbp", models.IntegerField(verbose_name="死球")),
                ("runs_allowed", models.IntegerField(verbose_name="失点")),
                ("earned_runs", models.IntegerField(verbose_name="自責点")),
                ("wild_pitches", models.IntegerField(verbose_name="暴投")),
                ("starter", models.BooleanField(default=False, verbose_name="先発")),
                (
                    "complete_game",
                    models.BooleanField(default=False, verbose_name="完投"),
                ),
                ("shutout", models.BooleanField(default=False, verbose_name="完封")),
                ("wins", models.IntegerField(verbose_name="勝利")),
                ("losses", models.IntegerField(verbose_name="敗戦")),
                ("saves", models.IntegerField(verbose_name="セーブ")),
                ("balks", models.IntegerField(verbose_name="ボーク")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matches.match",
                        verbose_name="試合",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="選手",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="チーム",
                    ),
                ),
            ],
            options={"db_table": "pitcher_stats",},
        ),
    ]
