# Generated by Django 5.1.2 on 2024-10-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hitterstat", old_name="game", new_name="match",
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="position",
            field=models.CharField(
                choices=[
                    ("P", "ピッチャー"),
                    ("C", "キャッチャー"),
                    ("1B", "ファースト"),
                    ("2B", "セカンド"),
                    ("3B", "サード"),
                    ("SS", "ショート"),
                    ("LF", "レフト"),
                    ("CF", "センター"),
                    ("RF", "ライト"),
                    ("DH", "DH"),
                ],
                max_length=50,
                verbose_name="ポジション",
            ),
        ),
    ]
