# Generated by Django 5.1.2 on 2024-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_rename_game_hitterstat_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hitterstat",
            name="at_bats",
            field=models.IntegerField(default=0, verbose_name="打数"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="caught_stealing",
            field=models.IntegerField(default=0, verbose_name="盗塁死"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="doubles",
            field=models.IntegerField(default=0, verbose_name="二塁打"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="errors",
            field=models.IntegerField(default=0, verbose_name="失策"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="gdp",
            field=models.IntegerField(default=0, verbose_name="併殺打"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="hbp",
            field=models.IntegerField(default=0, verbose_name="死球"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="hits",
            field=models.IntegerField(default=0, verbose_name="ヒット"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="home_runs",
            field=models.IntegerField(default=0, verbose_name="本塁打"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="plate_appearances",
            field=models.IntegerField(default=0, verbose_name="打席数"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="rbi",
            field=models.IntegerField(default=0, verbose_name="打点"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="runs",
            field=models.IntegerField(default=0, verbose_name="得点"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="sac_bunt",
            field=models.IntegerField(default=0, verbose_name="犠打"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="sac_fly",
            field=models.IntegerField(default=0, verbose_name="犠飛"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="steals",
            field=models.IntegerField(default=0, verbose_name="盗塁"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="strikeouts",
            field=models.IntegerField(default=0, verbose_name="三振"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="triples",
            field=models.IntegerField(default=0, verbose_name="三塁打"),
        ),
        migrations.AlterField(
            model_name="hitterstat",
            name="walks",
            field=models.IntegerField(default=0, verbose_name="四球"),
        ),
    ]
