# Generated by Django 5.1.2 on 2024-11-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_alter_hitterstat_at_bats_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pitcherstat",
            old_name="game",
            new_name="match",
        ),
    ]
