# Generated by Django 5.1.2 on 2024-11-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_rename_game_pitcherstat_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitcherstat",
            name="at_bats",
            field=models.IntegerField(default=0, verbose_name="打数"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="balks",
            field=models.IntegerField(default=0, verbose_name="ボーク"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="doubles_allowed",
            field=models.IntegerField(default=0, verbose_name="被二塁打"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="earned_runs",
            field=models.IntegerField(default=0, verbose_name="自責点"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="hbp",
            field=models.IntegerField(default=0, verbose_name="死球"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="hits_allowed",
            field=models.IntegerField(default=0, verbose_name="被安打"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="home_runs_allowed",
            field=models.IntegerField(default=0, verbose_name="被本塁打"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="losses",
            field=models.IntegerField(default=0, verbose_name="敗戦"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="plate_appearances",
            field=models.IntegerField(default=0, verbose_name="打席数"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="runs_allowed",
            field=models.IntegerField(default=0, verbose_name="失点"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="saves",
            field=models.IntegerField(default=0, verbose_name="セーブ"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="strikeouts",
            field=models.IntegerField(default=0, verbose_name="三振"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="triples_allowed",
            field=models.IntegerField(default=0, verbose_name="被三塁打"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="walks",
            field=models.IntegerField(default=0, verbose_name="四球"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="wild_pitches",
            field=models.IntegerField(default=0, verbose_name="暴投"),
        ),
        migrations.AlterField(
            model_name="pitcherstat",
            name="wins",
            field=models.IntegerField(default=0, verbose_name="勝利"),
        ),
    ]
